### ISSUE TITLE
Include HTTPS on demand

### ISSUE THREAD

**Issue by tiktaz** [pa-de-solminihac/dev-docker#2]
As many website used HTTPS as procotol, he would be welcome to launch container with this protocol or not. Container may test at launch if a dev/certifs directoy exists and then to choose what protocol to use

**Comment by pa-de-solminihac** [comment]
Your container is not bound to HTTP or HTTPS. You can have both enabled at the same time. HTTPS is enabled on a per-virtualhost basis.

For development purpose, you could [setup your own self-signed wildcard SSL certificate](http://stackoverflow.com/questions/1822268/how-do-i-create-my-own-wildcard-certificate-on-linux) so that you can serve *.myuser.mydomain.com with HTTPS.

Then `mkdir ~/dev/apache2/certificates` and put your `.pem` and `.key` files in it.

Finally, use this example apache config file to setup you virtualhost :
```apache
<VirtualHost *:443>
    ServerAdmin myuser@mydomain.com
    UseCanonicalName Off
    VirtualDocumentRoot /var/www/html/%1
    ServerName myhostname
    ServerAlias *.pa.quai13.com
    ErrorLog /var/log/dockersite/myuser-error_log
    CustomLog /var/log/dockersite/myuser-access_log dockersite
    SSLEngine on
    SSLCertificateFile /etc/apache2/dockersite/certificates/host.pem
    SSLCertificateKeyFile /etc/apache2/dockersite/certificates/host.key
</VirtualHost>
```

**Comment by whaze** [comment]
voir https://github.com/pa-de-solminihac/dev-docker/wiki/G%C3%A9rer-le-HTTPS
